---
title: "Looping"
author: "Adam Canton"
date: "6/7/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(matrixStats)
library(FNN)
library(MASS)
```

```{r}
# Set number of times you would like to repeat the sampling/testing - currently 500
iterations = 1:500

# the initial values for the columns (might not need these now that ive switched to building columns) 
rmse1 = c()
rmse2 = c()
rmse3 = c()

# Start of Loop
for(i in iterations){
  # Resets sample every iteration 
  index<- sample(1:dim(Life14)[1],128,replace=F)
  train<- Life14[index,]
  test<- Life14[-index,]
  
  # the model runs -  feel free to change them up and see what comes out
  modeltest1 <- lm(Life.expectancy ~ Adult.Mortality + SchoolFactor + LHIV.AIDS + percentage.expenditure + Total.expenditure + Linfant.deaths , data = train)
  
  modeltest2 <- lm(Life.expectancy ~ SchoolFactor + LHIV.AIDS + Adult.Mortality + percentage.expenditure + 
                   Linfant.deaths + Status + LGDP + Diphtheria , data = train)
  
  modeltest3 <- lm(Life.expectancy ~ Adult.Mortality, data = train)
  
  # predictors and column building
  predictions1 <- modeltest1 %>% predict(test)
  
  d1 = data.frame(R2 = R2(predictions1,test$Life.expectancy),
                  RMSE = RMSE(predictions1,test$Life.expectancy), MAE = MAE(predictions1, test$Life.expectancy))
  rmse1 = c(rmse1,d1$RMSE)
  
  predictions2 <- modeltest2 %>% predict(test)

  d2 = data.frame(R2 = R2(predictions2,test$Life.expectancy),
                RMSE = RMSE(predictions2,test$Life.expectancy), MAE = MAE(predictions2, test$Life.expectancy))
  rmse2 = c(rmse2, d2$RMSE)
  
  predictions3 <- modeltest3 %>% predict(test)

  d3 = data.frame(R2 = R2(predictions3,test$Life.expectancy),
                RMSE = RMSE(predictions3,test$Life.expectancy), MAE = MAE(predictions3, test$Life.expectancy))
  rmse3 = c(rmse3, d3$RMSE)
  # End for
}
# putting the dataframe together and outputting relevant statistics
Model.Average.RMSE = cbind(rmse1, rmse2, rmse3)
rmsedf = as.data.frame(Model.Average.RMSE)
Means = colMeans(Model.Average.RMSE)
SDs = round(colSds(Model.Average.RMSE), 3)
range1 = max(rmsedf$rmse1) - min(rmsedf$rmse1)
range2 = max(rmsedf$rmse2) - min(rmsedf$rmse2)
range3 = max(rmsedf$rmse3) - min(rmsedf$rmse3)

# Looking at range of each model to determine how variant it is - can also look at stats above
Means
print("Standard Devs")
SDs
print("ranges - measure of variance between train/test shuffles")
print(paste("Model 1 Range" , round(range1, 3)))
print(paste("Model 2 Range" , round(range2, 3)))
print(paste("Model 3 Range" , round(range3, 3)))
cat("Summary: 
    ")
summary(Model.Average.RMSE)


```
```{r}
# Set knn vectors - these are the column #s that will be analyzed 
knnvector1 = c(3,6,12,20)
knnvector2 = c(3,6,13,26:30)
knnvector3 = c(3,6,13,20)

# Start of Loop Variables
iterations = 1:500
i = 0
knnrmse1 = c()
knnrmse2 = c()
knnrmse3 = c()

# Loop start
for(i in iterations){
  # Create train and test sets
  index<-sample(1:dim(Life14Scale)[1],128,replace=F)
  train<-Life14Scale[index,]
  test<-Life14Scale[-index,]


  #KNN1
  predknn1 <- knn.reg(train[,knnvector1], test[, knnvector1], train$Life.expectancy, k = 3)
  Knn_Predictions_1 = as.data.frame(predknn1$pred)
  names(Knn_Predictions_1)[1] <- "Predictions"

  trial <- data.frame(Predictions = c(Knn_Predictions_1), Actual = c(test$Life.expectancy))

  trial = trial %>% mutate(ResidualSq1 = (Predictions - Actual)^2)

  RMSEknn1 = sqrt(sum((trial$ResidualSq1)/nrow(test)))
  knnrmse1 = c(knnrmse1, RMSEknn1)

  #KNN2
  predknn2 <- knn.reg(train[,knnvector2], test[, knnvector2], train$Life.expectancy, k = 3)
  Knn_Predictions_2 = as.data.frame(predknn2$pred)
  names(Knn_Predictions_2)[1] <- "Predictions"

  trial <- data.frame(Predictions = c(Knn_Predictions_2), Actual = c(test$Life.expectancy))

  trial = trial %>% mutate(ResidualSq2 = (Predictions - Actual)^2)

  RMSEknn2 = sqrt(sum((trial$ResidualSq2)/nrow(test)))
  knnrmse2 = c(knnrmse2, RMSEknn2)

  # KNN3
  predknn3 <- knn.reg(train[,knnvector3], test[, knnvector3], train$Life.expectancy, k = 3)
  Knn_Predictions_3 = as.data.frame(predknn3$pred)
  names(Knn_Predictions_3)[1] <- "Predictions"

  trial <- data.frame(Predictions = c(Knn_Predictions_3), Actual = c(test$Life.expectancy))

  trial = trial %>% mutate(ResidualSq3 = (Predictions - Actual)^2)

  RMSEknn3 = sqrt(sum((trial$ResidualSq3)/nrow(test)))
  knnrmse3 = c(knnrmse3, RMSEknn3)
  # End For
}

# putting the dataframe together and outputting relevant statistics
Knn.Model.Average.RMSE = cbind(knnrmse1, knnrmse2, knnrmse3)
knnrmsedf = as.data.frame(Knn.Model.Average.RMSE)
Means = colMeans(Knn.Model.Average.RMSE)
SDs = round(colSds(Knn.Model.Average.RMSE), 3)
knnrange1 = max(knnrmsedf$knnrmse1) - min(knnrmsedf$knnrmse1)
knnrange2 = max(knnrmsedf$knnrmse2) - min(knnrmsedf$knnrmse2)
knnrange3 = max(knnrmsedf$knnrmse3) - min(knnrmsedf$knnrmse3)

# Looking at range of each model to determine how variant it is - can also look at stats above
Means
print("Standard Devs")
SDs
print("ranges - measure of variance between train/test shuffles")
print(paste("Model 1 Range" , round(knnrange1, 3)))
print(paste("Model 2 Range" , round(knnrange2, 3)))
print(paste("Model 3 Range" , round(knnrange3, 3)))
cat("Summary: 
    ")
summary(Knn.Model.Average.RMSE)


```




